### ISSUE TITLE
contact details

### ISSUE THREAD

**Issue by mynumu** [trizmo/SalesGPT---Twilio#1]
hey how do we get in contact with you. Trying to identify if theres some malicious code in your repo thanks

**Comment by trizmo** [comment]
I'm in the SalesGPT discord server @trizmoto

**Comment by trizmo** [comment]
Closing this since contact details are provided.

**Comment by mynumu** [comment]
Hi cant find them my friend. So cloned this repo and started it with verbose debug in main.py and it’s somehow using an openai key from another organisation name thats not mine. I created a new openai key to test this . Now the crazy part is that other organisation is the name of a company I did a demo for last year. Nothing to do with this repo. There’s no link between us. It’s never happened before. I’ve deleted all my API keys in case it’s openai…and had to delete this repo.

also a random uuidlitellm.txt file appears when you run the main.py and it has an instance ID in the txt file. This file is not in the GitHub code tree.

im not running LiteLLM and can’t find any code reference to this uuid file

is there some leftover LiteLLM config in the code or is it malware??

why is it generating a LiteLLM uuid. I

It’s also throwing a lot of render.com errors in debug

Thoughts?. 

Just thought you may want to know..

**Comment by trizmo** [comment]
Openai key will be from your .env file. ChatLiteLLM is part of the run.py file.

**Comment by mynumu** [comment]
Yes..ok…but it’s not using the openaikey assigned by me and my organisation name! The header debug shows it’s using an openai key from a totally different organisation but billing my account…So either my openAI account was hacked as soon as I ran this or something weird is going on…

Ps apart from that…was cool seeing it working with the voice added!
